### PR TITLE
Fix skeletons url

### PR DESCRIPTION
**Pull request by yavorsky**

### CODE REVIEW

**Comment by es128** [comment]
Use the brunch.io one. It links to the wiki

**Comment by yavorsky** [comment]
@es128 but according to http://brunch.io/skeletons.html , the full list is at https://github.com/brunch/brunch/wiki/Skeletons . Ok, brunch.io is shorter)

**Comment by es128** [comment]
Yep b/c it's shorter - easier to type & remember. Also you can omit the .html

**Comment by es128** [comment]
And TBH there is no "full list". Neither page is being maintained all that well. The wiki has the advantage that anyone can edit it without a PR, although recently that led to a problem when someone listed something that wasn't actually a working skeleton.

**Comment by yavorsky** [comment]
Resolves brunch/brunch#927

**Comment by yavorsky** [comment]
@es128 thanks)

**Comment by paulmillr** [comment]
I've fixed the old link

**Comment by paulmillr** [comment]
but hte change is still ok

**Pull request merged**
